name: Ping my computer on code push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send HTTP request
      run: |
        curl https://cf6f-184-148-107-164.ngrok.io
